DROP TABLE IF EXISTS PROFESORES CASCADE;

CREATE TABLE PROFESORES (
	id_profesor INTEGER AUTO_INCREMENT PRIMARY KEY,
	nombre VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS CURSOS;

CREATE TABLE CURSOS (
  	id_curso INTEGER AUTO_INCREMENT NOT NULL,
  	titulo VARCHAR(255) NOT NULL UNIQUE,
  	activo BOOLEAN,
  	id_profesor INTEGER NOT NULL,
  	horas DOUBLE,
  	nivel ENUM('BASICO','INTERMEDIO','AVANZADO'),
  	
  	CONSTRAINT PK_CURSO PRIMARY KEY(id_curso, titulo),
  	CONSTRAINT FK_CURSO_PROFESOR FOREIGN KEY (id_profesor) REFERENCES PROFESORES(id_profesor)

);